### PR TITLE
A simple cross build supports both scala 2.10 and 2.11 

### PR DESCRIPTION
**Pull request by pzang**

### CODE REVIEW

**Comment by pzang** [comment]
Thanks for the library, and I have a project using scala 2.10 so it'll be nice to use cross build and publish to public repo for use.

**Comment by ruippeixotog** [comment]
Hi @pzang, thanks for the pull request! It looks good to me, as long as all the code works in Scala 2.10. Can you add Scala 2.10.5 to `.travis.yml` so that we can be sure?

**Comment by pzang** [comment]
Hi @ruippeixotog , sorry I didn't had a chance to look into this until the weekend, so I just added the travis build and seems passed, except for the coverage.

**Comment by ruippeixotog** [comment]
Ok, LGTM!

**Comment by ruippeixotog** [comment]
Ok, after merging I found out that Travis was not really running the build with Scala 2.10.5 as `.travis.yml` has its `script` field customized. After [I fixed the build](https://github.com/ruippeixotog/scala-scraper/commit/7351fcb56c03a5ef4c173d2f40109cfeb24140aa) to run the tests with Scala 2.10.x (I used 2.10.6 as it's the latest 2.10.x version, I hope it suits you) the tests [doesn't compile](https://travis-ci.org/ruippeixotog/scala-scraper/jobs/104430809)...

Can you fix this? Otherwise I may need to revert this PR. I'm sorry for the trouble.

**Comment by pzang** [comment]
@ruippeixotog  sorry I was pretty busy before and just saw this, so I made the change and  it seems passing the tests for both 2.10 and 2.11 in travis. Do you want to reopen this?

**Comment by ruippeixotog** [comment]
Hi @pzang! Sure, please leave this PR closed and submit another pull request with the new changes. Depending on the scope of the changes required to the source code I don't mind supporting both Scala 2.10 and Scala 2.11, but only as long as that doesn't keep me from using relevant Scala features.

**Pull request merged**
